### ISSUE TITLE
how to play ai?

### ISSUE THREAD

**Issue by cloudjanak** [avd-cs534/Scrabble#1]
is it possiable like below in web-site 
pass the current board and it will return all playable words with starting position and direction.

http://www.lexicalwordfinder.com/?game=Words_With_Friends&layout=1&tiles=gtsfsdf&board=----------------------------------------------------------------------------------------------------------------hello------------------------------------------------------------------------------------------------------------&lexicon=wwf

**Comment by avd-cs534** [comment]
Unfortunately not. Since we had limited time, we had to design and implement it in a quick fashion. It's limited to 2 users.
